paul_user:
    resource: "@PaulUserBundle/Resources/config/routing.yml"
    prefix:   /

paul_timeline:
    resource: "@PaulTimelineBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"