<?php

namespace Paul\TimelineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findAllPublic()
    {
        $qb = $this->createQueryBuilder('p');

        $qb->where("p.published = true");

        $query = $qb->getQuery();

        $results = $query->getResult();

        return $results;
    }
}
