security:

    encoders:
            FOS\UserBundle\Model\UserInterface: sha512

    providers:
            fos_userbundle:
                id: fos_user.user_provider.username

    firewalls:
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false

            main:
                pattern: .*
                form_login:
                    provider:      fos_userbundle
                    csrf_provider: form.csrf_provider
                    login_path:    fos_user_security_login
                    check_path:    fos_user_security_check
                    always_use_default_target_path: false
                    default_target_path: /profile
                    use_forward:   false
                    failure_path: null
                    remember_me:   true
                remember_me:
                    key:           %secret%
                    lifetime:      3000000

                logout:            true
                anonymous:         true