
post_list:
    path:     /
    defaults: { _controller: PaulTimelineBundle:Post:list }

post_create:
    path:     /admin/post/create
    defaults: { _controller: PaulTimelineBundle:Post:create }

post_view:
    path:     /post/{id}/view
    defaults: { _controller: PaulTimelineBundle:Post:view }
    requirements:
        id: \d+