
post_list:
    path:     /
    defaults: { _controller: PaulTimelineBundle:Post:list }

post_create:
    path:     /post/create
    defaults: { _controller: PaulTimelineBundle:Post:create }

post_update:
    path:     /post/{id}/update
    defaults: { _controller: PaulTimelineBundle:Post:update }
    requirements:
            id: \d+

post_view:
    path:     /post/{id}/view
    defaults: { _controller: PaulTimelineBundle:Post:view }
    requirements:
        id: \d+